# Bar, wallpaper
exec-once = ironbar
exec-once = hyprpaper
exec-once = wl-paste --watch cliphist store
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME
exec-once = /usr/lib/x86_64-linux-gnu/libexec/polkit-kde-authentication-agent-1
# Input method
exec-once = fcitx5
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.config/hypr/portal.sh
exec-once = ~/.config/hypr/settheme.sh
exec-once = wf-background
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets
# Notification
exec-once = mako
