# Bar, wallpaper
exec-once = ~/.cargo/bin/ironbar
# exec-once = ulauncher
exec-once = USE_LAYER_SHELL=0 vicinae server
# exec-once = hyprpaper
# exec-once = wf-background
exec-once = fish -c "waypaper --restore"
exec-once = wl-paste --watch cliphist store
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME
exec-once = /usr/libexec/hyprpolkitagent
# Input method
exec-once = fcitx5
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.config/hypr/portal.sh
exec-once = ~/.config/hypr/settheme.sh
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets
# Notification
exec-once = mako
exec-once = ~/.local/bin/pypr
