# windowrule = no_blur on, match:class ^(foot)$
# windowrule = no_blur on, match:class ^(Emacs)$
# windowrule = no_blur on, match:class ^(neovide)$
# windowrule = no_blur on, match:class ^(Alacritty)$
# windowrule = no_blur on, match:class ^(dev.zed.Zed)$

# Window rules
windowrule = float on, match:class ^(steam)$
windowrule = float on, match:class ^(wechat)$
windowrule = float on, match:class ^(QQ)$

# Dialogs
windowrule = center on, match:title ^(Open File)(.*)$
windowrule = center on, match:title ^(Select a File)(.*)$
windowrule = center on, match:title ^(Choose wallpaper)(.*)$
windowrule = center on, match:title ^(Open Folder)(.*)$
windowrule = center on, match:title ^(Save As)(.*)$
windowrule = center on, match:title ^(Library)(.*)$
windowrule = center on, match:title ^(File Upload)(.*)$
windowrule = float on, match:title ^(Open File)(.*)$
windowrule = float on, match:title ^(Select a File)(.*)$
windowrule = float on, match:title ^(Choose wallpaper)(.*)$
windowrule = float on, match:title ^(Open Folder)(.*)$
windowrule = float on, match:title ^(Save As)(.*)$
windowrule = float on, match:title ^(Library)(.*)$
windowrule = float on, match:title ^(File Upload)(.*)$
windowrule = float on, match:title ^(微信)(.*)$

windowrule = float on, match:class ^(ulauncher|albert|vicinae)$
windowrule = no_blur on, match:class ^(ulauncher|albert|vicinae)$
windowrule = pin on, match:class ^(ulauncher|albert|vicinae)$
windowrule = stay_focused on, match:class ^(ulauncher|albert|vicinae)$
windowrule = border_size 0, match:class ^(ulauncher|albert|vicinae)$

windowrule = float on, match:title ^(holo_layer.py)$
windowrule = no_blur on, match:title ^(holo_layer.py)$
windowrule = no_anim on, match:title ^(holo_layer.py)$
# windowrule = monitor 1, class:(holo_layer.py)
# windowrule = fakefullscreen,title:(holo_layer.py)

# Flameshot
windowrule = no_anim on, match:class ^(flameshot)$
# windowrule = float, class:^(flameshot)$
windowrule = move 0 0, match:class ^(flameshot)$
windowrule = pin on, match:class ^(flameshot)$
# windowrule = noinitialfocus, class:^(flameshot)$
windowrule = monitor 1, match:class ^(flameshot)$
