[terminal.shell]
program = "/usr/bin/bash"
args = [
    "-l",
    "-c",
    "/home/noilinux/.cargo/bin/zellij attach --index 0 || /home/noilinux/.cargo/bin/zellij"
]

[env]
TERM="xterm-256color"

[window]
opacity = 0.8

[font]
size = 16
normal = { family = "LXGWWenKaiMono Nerd Font" }
bold = { family = "LXGWWenKaiMono Nerd Font" }
italic = { family = "LXGWWenKaiMono Nerd Font" }

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[general]
import = [
    "~/.config/alacritty/mocha.toml"
]

[terminal]

