import = [
    "~/.config/alacritty/mocha.toml"
]

[window]
opacity = 1.0

[font]
size = 14.0
normal = { family = "VictorMono Nerd Font" }
bold = { family = "VictorMono Nerd Font" }
italic = { family = "VictorMono Nerd Font" }

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
