import = [
    "~/.config/alacritty/mocha.toml"
]

[window]
opacity = 1.0

[font]
size = 12.0
normal = { family = "Maple Mono NF" }
bold = { family = "Maple Mono NF" }
italic = { family = "Maple Mono NF" }

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
