[env]
TERM="xterm-256color"

[window]
decorations = "None"
opacity = 0.8

[font]
size = 14
normal = { family = "JetbrainsMono Nerd Font" }
bold = { family = "JetbrainsMono Nerd Font" }
italic = { family = "JetbrainsMono Nerd Font" }

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[general]
import = [
    "~/.config/alacritty/catppuccin-frappe.toml"
]

[terminal]

