bind = Ctrl Shift, Escape, exec, dms ipc call processlist open # Task Manager: Open
bind = Super, I, exec, dms ipc call settings open # Settings: Open
bind = Super, M, exec, dms ipc call powermenu toggle # Power Menu: Toggle
bind = Super Shift, N, exec, dms ipc call notifications toggle # Notifications: Toggle
bind = Super, T, exec, dms ipc call notepad toggle # Notepad: Toggle
bind = Super, Tab, exec, dms ipc call hypr toggleOverview # Hyprland: Toggle Overview
bind = Super, V, exec, dms ipc call clipboard toggle # Clipboard: Toggle
bind = Super, X, exec, dms ipc call lock lock # Lock Screen
bind = Super, space, exec, dms ipc call spotlight toggle # App Launcher: Toggle
bind = Super, 1, workspace, 1 # Focus Workspace 1
bind = Super, 2, workspace, 2 # Focus Workspace 2
bind = Super, 3, workspace, 3 # Focus Workspace 3
bind = Super, 4, workspace, 4 # Focus Workspace 4
bind = Super, 5, workspace, 5 # Focus Workspace 5
bind = Super, 6, workspace, 6 # Focus Workspace 6
bind = Super, 7, workspace, 7 # Focus Workspace 7
bind = Super, 8, workspace, 8 # Focus Workspace 8
bind = Super, 9, workspace, 9 # Focus Workspace 9
bind = Super Ctrl, Left, workspace, -1 # Previous Workspace
bind = Super Ctrl, Right, workspace, +1 # Next Workspace
bind = Super Ctrl Shift, Tab, movetoworkspace, previous # Move to Previos Visited Workspace
bind = Super Ctrl, Tab, workspace, previous # Previous Visited Workspace
bind = Super Shift, 1, movetoworkspace, 1 # Move to Workspace 1
bind = Super Shift, 2, movetoworkspace, 2 # Move to Workspace 2
bind = Super Shift, 3, movetoworkspace, 3 # Move to Workspace 3
bind = Super Shift, 4, movetoworkspace, 4 # Move to Workspace 4
bind = Super Shift, 5, movetoworkspace, 5 # Move to Workspace 5
bind = Super Shift, 6, movetoworkspace, 6 # Move to Workspace 6
bind = Super Shift, 7, movetoworkspace, 7 # Move to Workspace 7
bind = Super Shift, 8, movetoworkspace, 8 # Move to Workspace 8
bind = Super Shift, 9, movetoworkspace, 9 # Move to Workspace 9
bind = Super, WheelScrollDown, workspace, e-1 # Previous Open Workspace
bind = Super, WheelScrollUp, workspace, e+1 # Next Open Workspace
bind = Super, H, movefocus, l # Move Focus Left
bind = Super, J, movefocus, d # Move Focus Down
bind = Super, K, movefocus, u # Move Focus Up
bind = Super, L, movefocus, r # Move Focus Right
bind = Super Shift, H, movewindow, l # Move Window Left
bind = Super Shift, J, movewindow, d # Move Window Down
bind = Super Shift, K, movewindow, u # Move Window Up
bind = Super Shift, L, movewindow, r # Move Window Right
bind = Super, D, exec, vicinae toggle # Open Vicinae
bind = Super, Equal, exec, pyprclient zoom +0.5 # Zoom In
bind = Super, Escape, exec, pyprclient zoom # Toggle Zoom
bind = Super, Minus, exec, pyprclient zoom -0.5 # Zoom Out
bind = Super, N, exec, nautilus # Open Nautilus
bind = Super, P, exec, hyprpicker -n -a # Pick Color in the Screen
bind = Super, R, exec, rofi -show run # Open Shell Executor
bind = Super, Return, exec, kitty # Open Kitty Terminal
bind = Super, S, exec, HYPRQUICKFRAME_EDITOR=1 quickshell -c HyprQuickFrame -n # Screenshot
bind = Super Shift, Z, exec, pkill gpu-screen-reco # Stop Record Screen
bind = Super, U, exec, code-insiders --ozone-platform=wayland --enable-features=useozoneplatform --enable-wayland-ime --password-store=gnome-libsecret # Open VSCode Insiders
bind = Super, W, exec, wezterm # Open Wezterm
bind = Super, Z, exec, gpu-screen-recorder -w region -region "$(slurp -f %wx%h+%x+%y)" -f 60 -a "default_output" -o ~/下载/recording_$(date +%Y%m%d_%H%M%S).mp4 # Record Screen
bind = Super, F, fullscreen # Toggle Fullscreen
bind = Super, Q, killactive # Close Window
bind = Super Shift, space, togglefloating # Toggle Floating
