-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("CTRL + SHIFT + Escape")
hl.bind("CTRL + SHIFT + Escape", hl.dsp.exec_cmd("dms ipc call processlist open"), { description = "Open Task Manger" })
hl.unbind("SUPER + I")
hl.bind("SUPER + I", hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"), { description = "Toggle DMS Settings" })
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.exec_cmd("dms ipc call powermenu toggle"), { description = "Toggle Power Menu" })
hl.unbind("SUPER + SHIFT + N")
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("dms ipc call notifications toggle"), { description = "Toggle Notifications Center" })
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.exec_cmd("dms ipc call notepad toggle"), { description = "Toggle DMS Notepad" })
hl.unbind("SUPER + Tab")
hl.bind("SUPER + Tab", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"), { description = "Toggle Hyprland Overview" })
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"), { description = "Toggle Clipboard" })
hl.unbind("SUPER + X")
hl.bind("SUPER + X", hl.dsp.exec_cmd("dms ipc call lock lock"), { description = "Lock Screen" })
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.exec_cmd("dms ipc call spotlight toggle"), { description = "Open Spotlight" })
hl.unbind("SUPER + CTRL + Left")
hl.bind("SUPER + CTRL + Left", hl.dsp.focus({ workspace = "-1" }), { description = "Previous Workspace" })
hl.unbind("SUPER + CTRL + Right")
hl.bind("SUPER + CTRL + Right", hl.dsp.focus({ workspace = "+1" }), { description = "Next Workspace" })
hl.unbind("SUPER + CTRL + SHIFT + Tab")
hl.bind("SUPER + CTRL + SHIFT + Tab", hl.dsp.window.move({ workspace = "previous" }))
hl.unbind("SUPER + CTRL + Tab")
hl.bind("SUPER + CTRL + Tab", hl.dsp.focus({ workspace = "previous" }), { description = "Previous Visited Workspace" })
hl.unbind("SUPER + mouse_down")
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e-1" }), { description = "Previous Open Workspace" })
hl.unbind("SUPER + mouse_up")
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e+1" }), { description = "Next Open Workspace" })
hl.unbind("SUPER + H")
hl.bind("SUPER + H", hl.dsp.focus({ direction = "l" }))
hl.unbind("SUPER + J")
hl.bind("SUPER + J", hl.dsp.focus({ direction = "d" }))
hl.unbind("SUPER + K")
hl.bind("SUPER + K", hl.dsp.focus({ direction = "u" }))
hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.focus({ direction = "r" }))
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.exec_cmd("vicinae toggle"), { description = "Toggle Vicinae" })
hl.unbind("SUPER + Equal")
hl.bind("SUPER + Equal", hl.dsp.exec_cmd("pyprclient zoom +0.5"), { description = "Zoom In" })
hl.unbind("SUPER + Escape")
hl.bind("SUPER + Escape", hl.dsp.exec_cmd("pyprclient zoom"), { description = "Toggle Zoom" })
hl.unbind("SUPER + Minus")
hl.bind("SUPER + Minus", hl.dsp.exec_cmd("pyprclient zoom -0.5"), { description = "Zoom Out" })
hl.unbind("SUPER + N")
hl.bind("SUPER + N", hl.dsp.exec_cmd("nautilus"), { description = "Open File Manager" })
hl.unbind("SUPER + P")
hl.bind("SUPER + P", hl.dsp.exec_cmd("hyprpicker -n -a"), { description = "Pick Color" })
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.exec_cmd("rofi -show run"), { description = "Open Rofi" })
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"), { description = "Open Kitty" })
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.exec_cmd("HQF_ACTION=edit quickshell -c HyprQuickFrame -n"), { description = "Screenshot" })
hl.unbind("SUPER + SHIFT + Z")
hl.bind("SUPER + SHIFT + Z", hl.dsp.exec_cmd("pkill gpu-screen-reco"), { description = "Stop Screen Record" })
hl.unbind("SUPER + Z")
hl.bind("SUPER + Z", hl.dsp.exec_cmd("gpu-screen-recorder -w region -region \"$(slurp -f %wx%h+%x+%y)\" -f 60 -a \"default_output\" -o ~/下载/recording_$(date +%Y%m%d_%H%M%S).mp4"), { description = "Start Screen Record" })
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.unbind("SUPER + SHIFT + Q")
hl.bind("SUPER + SHIFT + Q", hl.dsp.window.kill(), { description = "Force Kill Window" })
hl.unbind("SUPER + SHIFT + space")
hl.bind("SUPER + SHIFT + space", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle Floating" })
hl.unbind("SUPER + U")
hl.unbind("SUPER + W")
