-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("CTRL + SHIFT + Escape")
hl.bind("CTRL + SHIFT + Escape", hl.dsp.exec_cmd("dms ipc call processlist open"))
hl.unbind("SUPER + I")
hl.bind("SUPER + I", hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"))
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.exec_cmd("dms ipc call powermenu toggle"))
hl.unbind("SUPER + SHIFT + N")
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("dms ipc call notifications toggle"))
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.exec_cmd("dms ipc call notepad toggle"))
hl.unbind("SUPER + Tab")
hl.bind("SUPER + Tab", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"))
hl.unbind("SUPER + X")
hl.bind("SUPER + X", hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
hl.unbind("SUPER + CTRL + Left")
hl.bind("SUPER + CTRL + Left", hl.dsp.focus({ workspace = -1 }))
hl.unbind("SUPER + CTRL + Right")
hl.bind("SUPER + CTRL + Right", hl.dsp.focus({ workspace = "+1" }))
hl.unbind("SUPER + CTRL + SHIFT + Tab")
hl.bind("SUPER + CTRL + SHIFT + Tab", hl.dsp.window.move({ workspace = "previous" }))
hl.unbind("SUPER + CTRL + Tab")
hl.bind("SUPER + CTRL + Tab", hl.dsp.focus({ workspace = "previous" }))
-- hl.unbind("SUPER + WheelScrollDown")
-- hl.bind("SUPER + WheelScrollDown", hl.dsp.exec_cmd("hyprctl dispatch workspace e-1"))
-- hl.unbind("SUPER + WheelScrollUp")
-- hl.bind("SUPER + WheelScrollUp", hl.dsp.exec_cmd("hyprctl dispatch workspace e+1"))
hl.unbind("SUPER + H")
hl.bind("SUPER + H", hl.dsp.focus({ direction = "l" }))
hl.unbind("SUPER + J")
hl.bind("SUPER + J", hl.dsp.focus({ direction = "d" }))
hl.unbind("SUPER + K")
hl.bind("SUPER + K", hl.dsp.focus({ direction = "u" }))
hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.focus({ direction = "r" }))
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.exec_cmd("vicinae toggle"))
hl.unbind("SUPER + Equal")
hl.bind("SUPER + Equal", hl.dsp.exec_cmd("pyprclient zoom +0.5"))
hl.unbind("SUPER + Escape")
hl.bind("SUPER + Escape", hl.dsp.exec_cmd("pyprclient zoom"))
hl.unbind("SUPER + Minus")
hl.bind("SUPER + Minus", hl.dsp.exec_cmd("pyprclient zoom -0.5"))
hl.unbind("SUPER + N")
hl.bind("SUPER + N", hl.dsp.exec_cmd("nautilus"))
hl.unbind("SUPER + P")
hl.bind("SUPER + P", hl.dsp.exec_cmd("hyprpicker -n -a"))
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.exec_cmd("rofi -show run"))
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"))
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.exec_cmd("HYPRQUICKFRAME_EDITOR=1 quickshell -c HyprQuickFrame -n"))
hl.unbind("SUPER + SHIFT + Z")
hl.bind("SUPER + SHIFT + Z", hl.dsp.exec_cmd("pkill gpu-screen-reco"))
hl.unbind("SUPER + U")
hl.bind("SUPER + U", hl.dsp.exec_cmd("code-insiders --ozone-platform=wayland --enable-features=useozoneplatform --enable-wayland-ime --password-store=gnome-libsecret"))
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("wezterm"))
hl.unbind("SUPER + Z")
hl.bind("SUPER + Z", hl.dsp.exec_cmd("gpu-screen-recorder -w region -region \"$(slurp -f %wx%h+%x+%y)\" -f 60 -a \"default_output\" -o ~/下载/recording_$(date +%Y%m%d_%H%M%S).mp4"))
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ action = "toggle" }))
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.unbind("SUPER + SHIFT + Q")
hl.bind("SUPER + SHIFT + Q", hl.dsp.window.kill())
hl.unbind("SUPER + SHIFT + space")
hl.bind("SUPER + SHIFT + space", hl.dsp.window.float({ action = "toggle" })) -- Toggle Floating
