-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "catppuccin-frappe-blue-cursors")
hl.env("XCURSOR_THEME", "catppuccin-frappe-blue-cursors")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_SIZE", "24")

hl.config({
	cursor = {
		hide_on_key_press = true,
	},
})
