hl.on("hyprland.start", function () 
  hl.exec_cmd("~/.config/hypr/portal.sh")
  hl.exec_cmd("/usr/libexec/hyprpolkitagent")
  hl.exec_cmd("~/.config/hypr/settheme.sh")
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("/usr/bin/gnome-keyring-daemon --start --components=secrets")
  hl.exec_cmd("dbus-update-activation-environment --systemd --all")
  hl.exec_cmd("systemctl --user import-environment QT_QPA_PLATFORMTHEME")
  hl.exec_cmd("hyprpm reload")
  hl.exec_cmd("vicinae server")
  hl.exec_cmd("dms run")
  hl.exec_cmd("wl-paste --watch cliphist store")
  hl.exec_cmd("fcitx5")
  hl.exec_cmd("~/.local/bin/pypr")
end)
