# ~/.config/kubeswitch.toml

cmd = "ks"
editor = "nvim"

[kube]
exec = "kubectl"
cmd = "k"
dir = "~/.kube/config"
export_kubeconfig = false
update_context = false

[k9s]
enable = true
exec = "k9s"
cmd = "kk"
