[pyprland]
plugins = [
  "scratchpads",
  "lost_windows",
  "monitors",
  "toggle_dpms",
  "magnify",
  "expose",
  "shift_monitors",
  "workspaces_follow_focus",
  "change_workspace",
]

[workspaces_follow_focus]
max_workspaces = 99

[scratchpads.term]
animation = "fromTop"
command = "alacritty --class alacritty-dropterm"
class = "alacritty-dropterm"
size = "75% 60%"
